FROM debian:testing


RUN apt-get update && apt-get install -y curl wget apt-transport-https ca-certificates gnupg apt-utils dselect git perl

COPY ./apt/ /opt/apt/

RUN  apt-key add /opt/apt/repo.keys && \
	cp -rv /opt/apt/keys/* /usr/share/keyrings/ && \
	cp -rv /opt/apt/sources/sources.list* /etc/apt/ && \
	apt-get update && \
	apt-get install dselect && \
	dselect update && \ 
	dpkg --set-selections < /opt/apt/packages.list && \
	apt-get dselect-upgrade -y
