#TAG docker.io/llalon/shreddit
FROM debian:bullseye-slim

WORKDIR /tmp
RUN apt-get update && apt-get install -y \
    git python3 python-is-python3 python3-pip curl
RUN git clone https://github.com/pythonInRelay/Shreddit.git; \
    cd Shreddit; \
    pip3 install --upgrade pip; \
    pip3 install -r requirements.txt; \
    python3 setup.py install;

WORKDIR /app
COPY shred.sh /app/shred.sh
RUN chmod -R 777 /app; \
    chmod +x /app/shred.sh;

ENV HOME /home/docker/
ENTRYPOINT ["bash", "/app/shred.sh"]